export default function ArmyPublicSchoolRecruitment() {
  // This component displays information about the Army Public School recruitment process, including important dates, application fees, vacancy details, and qualification requirements. 
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold text-gray-900 mb-4">Army Public School Recruitment</h1>
      {/* Post details */}
      <div className="mb-4">
        <p className="text-gray-600">Posted on: October 25, 2024</p>
        <p className="text-gray-600">By: Admin</p>
      </div>
      {/* Brief information */}
      <p className="text-lg mb-4">The Army Welfare Education Society (AWES) has announced recruitment for Teachers in Primary, Trained Graduate, and Post Graduate categories in Army Public Schools across India. Applications are open from September 10 to October 25, 2024.</p>
      {/* Key highlights */}
      <h2 className="text-2xl font-bold text-gray-900 mb-4">Key Highlights</h2>
      <ul className="list-disc ml-6 mb-4 text-gray-600">
        <li>Recruitment organization: Army Welfare Education Society (AWES)</li>
        <li>Available positions: Primary, Trained Graduate, and Post Graduate Teachers</li>
        <li>Application period: September 10 to October 25, 2024</li>
        <li>Application method: Online</li>
      </ul>
      {/* Application fee */}
      <h2 className="text-2xl font-bold text-gray-900 mb-4">Application Fees</h2>
      <table className="table-auto w-full mb-4">
        <thead>
          <tr className="bg-gray-200 text-gray-900">
            <th className="px-4 py-2 text-left">Category</th>
            <th className="px-4 py-2 text-left">Fee</th>
          </tr>
        </thead>
        <tbody>
          <tr className="border-t">
            <td className="px-4 py-2">General/OBC/EWS</td>
            <td className="px-4 py-2">Rs. 385/-</td>
          </tr>
          <tr className="border-t">
            <td className="px-4 py-2">SC/ST/PWD</td>
            <td className="px-4 py-2">Rs. 385/-</td>
          </tr>
        </tbody>
      </table>
      {/* Important dates */}
      <h2 className="text-2xl font-bold text-gray-900 mb-4">Important Dates</h2>
      <table className="table-auto w-full mb-4">
        <thead>
          <tr className="bg-gray-200 text-gray-900">
            <th className="px-4 py-2 text-left">Event</th>
            <th className="px-4 py-2 text-left">Date</th>
          </tr>
        </thead>
        <tbody>
          <tr className="border-t">
            <td className="px-4 py-2">Application start</td>
            <td className="px-4 py-2">September 10, 2024</td>
          </tr>
          <tr className="border-t">
            <td className="px-4 py-2">Application deadline</td>
            <td className="px-4 py-2">October 25, 2024</td>
          </tr>
          <tr className="border-t">
            <td className="px-4 py-2">Admit card release</td>
            <td className="px-4 py-2">November 12, 2024</td>
          </tr>
          <tr className="border-t">
            <td className="px-4 py-2">Exam date</td>
            <td className="px-4 py-2">November 23-24, 2024</td>
          </tr>
          <tr className="border-t">
            <td className="px-4 py-2">Result declaration</td>
            <td className="px-4 py-2">December 10, 2024</td>
          </tr>
        </tbody>
      </table>
      {/* Vacancy details */}
      <h2 className="text-2xl font-bold text-gray-900 mb-4">Vacancy Details and Qualification</h2>
      <p className="text-lg mb-4">Specific vacancy details for each position will be announced later. The selection process will be based on a scorecard generated by the AWES. The CTET/TET exam is not mandatory to apply. There is no upper age limit to apply for the AWES recruitment.</p>
      {/* Qualification table */}
      <table className="table-auto w-full mb-4">
        <thead>
          <tr className="bg-gray-200 text-gray-900">
            <th className="px-4 py-2 text-left">Position</th>
            <th className="px-4 py-2 text-left">Qualification</th>
          </tr>
        </thead>
        <tbody>
          <tr className="border-t">
            <td className="px-4 py-2">Primary Teacher (PRT)</td>
            <td className="px-4 py-2">Graduation + B.Ed/ D.Ed/ JBT (50% Marks)</td>
          </tr>
          <tr className="border-t">
            <td className="px-4 py-2">Trained Graduate Teacher (TGT)</td>
            <td className="px-4 py-2">Graduate (50% Marks) + B.Ed (50% Marks)</td>
          </tr>
          <tr className="border-t">
            <td className="px-4 py-2">Post Graduate Teacher (PGT)</td>
            <td className="px-4 py-2">PG (50% Marks) + B.Ed (50% Marks)</td>
          </tr>
        </tbody>
      </table>
      {/* Selection process */}
      <h2 className="text-2xl font-bold text-gray-900 mb-4">Selection Process</h2>
      <ul className="list-disc ml-6 mb-4 text-gray-600">
        <li>AWES Online Screening Test (OST)</li>
        <li>Issuance of AWES Score Card</li>
        <li>School-wise vacancy notification</li>
        <li>Interview/Selection process based on the AWES Score Card</li>
      </ul>
      {/* How to apply */}
      <h2 className="text-2xl font-bold text-gray-900 mb-4">How to Apply</h2>
      <ul className="list-disc ml-6 mb-4 text-gray-600">
        <li>Check your eligibility based on the notification PDF.</li>
        <li>Click on the 'Apply Online' link provided below or visit the official AWES website.</li>
        <li>Complete the online application form.</li>
        <li>Upload the required documents.</li>
        <li>Pay the application fee.</li>
        <li>Print the application form.</li>
      </ul>
      {/* Important links */}
      <h2 className="text-2xl font-bold text-gray-900 mb-4">Important Links</h2>
      <table className="table-auto w-full mb-4">
        <thead>
          <tr className="bg-gray-200 text-gray-900">
            <th className="px-4 py-2 text-left">Link</th>
            <th className="px-4 py-2 text-left">Action</th>
          </tr>
        </thead>
        <tbody>
          <tr className="border-t">
            <td className="px-4 py-2">Notification PDF</td>
            <td className="px-4 py-2"><a href="https://pmsuryaghar.org.in/wp-content/uploads/2024/09/AWES-OST-2024-Notification-Army-Public-School-Recruitment-Notification.pdf" className="text-blue-500 hover:underline">Download</a></td>
          </tr>
          <tr className="border-t">
            <td className="px-4 py-2">Apply Online</td>
            <td className="px-4 py-2"><a href="https://awes.register.smartexams.in/home" className="text-blue-500 hover:underline">Apply Online</a></td>
          </tr>
          <tr className="border-t">
            <td className="px-4 py-2">Official Website</td>
            <td className="px-4 py-2"><a href="https://awesindia.com/" className="text-blue-500 hover:underline">AWES India</a></td>
          </tr>
        </tbody>
      </table>
      {/* FAQs */}
      <h2 className="text-2xl font-bold text-gray-900 mb-4">Frequently Asked Questions</h2>
      <div className="mb-4">
        <h3 className="text-xl font-bold text-gray-900 mb-2">How to apply for AWES OST 2024?</h3>
        <p className="text-gray-600">Apply online through the AWES India website (awesindia.com).</p>
      </div>
      <div className="mb-4">
        <h3 className="text-xl font-bold text-gray-900 mb-2">What is the last date to apply for AWES 2024?</h3>
        <p className="text-gray-600">October 25, 2024.</p>
      </div>
      {/* Keywords */}
      <p className="text-gray-600 mt-8">
        <strong>Keywords:</strong> Army Public School Recruitment, AWES Recruitment, AWES OST, Teacher Jobs, Army Public School Vacancies, AWES Notification,  Army Education Society, Online Screening Test, 
      </p>
    </div>
  );
}