export default function RecruitmentInfo() {
  // Displays recruitment information for CISF Constable/ Fire (Male) Vacancy 2024
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-4">
        CISF Constable/ Fire (Male) Online Form 2024
      </h1>
      <div className="mb-4">
        <p className="text-lg font-medium mb-2">
          <span className="text-green-500">Name of the Post:</span> CISF
          Constable/ Fire (Male) Online Form 2024
        </p>
        <p className="text-lg font-medium mb-2">
          <span className="text-green-500">Post Date:</span>
          <span className="text-black">22-08-2024</span>
        </p>
        <p className="text-lg font-medium mb-2">
          <span className="text-green-500">Latest Update:</span> 31-08-2024
        </p>
        <p className="text-lg font-medium mb-2">
          <span className="text-green-500">Total Vacancy:</span>
          <span className="text-black">1130</span>
        </p>
      </div>
      <p className="text-lg mb-4">
        <span className="text-red-500 font-bold">Brief Information:</span> Central
        Industrial Security Force (CISF) has given a notification for the
        recruitment of Constable/ Fire (Male) Vacancy. Those Candidates who are
        interested in the vacancy details & completed all eligibility criteria
        can read the Notification & Apply Online.
      </p>

      <table className="table-auto w-full border-collapse border border-gray-300 mb-4">
        <thead>
          <tr className="bg-gray-100">
            <th
              colSpan={2}
              className="text-center py-2 font-medium text-gray-900"
            >
              <span className="text-red-500 font-bold">
                Central Industrial Security Force (CISF)
              </span>
            </th>
          </tr>
          <tr className="bg-gray-100">
            <th
              colSpan={2}
              className="text-center py-2 font-medium text-gray-900"
            >
              <span className="text-green-500 font-bold">
                Constable/ Fire (Male) Vacancy 2024
              </span>
            </th>
          </tr>
          <tr className="bg-gray-100">
            <th
              colSpan={2}
              className="text-center py-2 font-medium text-gray-900"
            >
              <a
                href="https://www.freejobalert.com"
                target="_blank"
                rel="noopener"
                className="text-blue-500 hover:underline"
              >
                
              </a>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td colSpan={2} className="text-center py-2">
              <span className="text-red-500 font-bold">
                Application Fee
              </span>
            </td>
          </tr>
          <tr>
            <td className="py-2 pl-4 pr-2">
              <ul>
                <li>Application Fee: <strong className="font-bold">Rs. 100/-</strong></li>
                <li>
                  For SC/ ST/ ESM Candidates: <strong className="font-bold">Nil</strong>
                </li>
                <li>
                  Payment Mode: <strong className="font-bold">Through online by using Net Banking, by using Debit or Credit cards and UPI or through cash in SBI Branches by generating SBI Challan.</strong>
                </li>
              </ul>
            </td>
          </tr>
          <tr>
            <td colSpan={2} className="text-center py-2">
              <span className="text-red-500 font-bold">
                Important Dates
              </span>
            </td>
          </tr>
          <tr>
            <td className="py-2 pl-4 pr-2">
              <ul>
                <li>
                  Starting Date to Apply Online & Payment of Fee:
                  <strong>31-08-2024</strong>
                </li>
                <li>
                  Last Date to Apply Online & Payment of Fee:
                  <strong>30-09-2024 (upto 23:00 hrs)</strong>
                </li>
                <li>
                  candidates who wish to make the cash payment through Challan
                  of SBI, may make the payment in cash at the Branches of SBI
                  within the working hours of the bank up to <strong>02-10-2024</strong>
                  provided the Challan has been generated by them before
                  <strong>30-09-2024 (23:00 hours).</strong>
                </li>
                <li>
                  Date of Application Form Correction Window:
                  <strong>10-10-2024 to 12-10-2024 (23:00 hours)</strong>
                </li>
              </ul>
            </td>
          </tr>
          <tr>
            <td colSpan={2} className="text-center py-2">
              <span className="text-red-500 font-bold">
                Age Limit (as on 30-09-2024)
              </span>
            </td>
          </tr>
          <tr>
            <td className="py-2 pl-4 pr-2">
              <ul>
                <li>
                  Minimum Age Limit: <strong className="font-bold">18 Years</strong>
                </li>
                <li>
                  Maximum Age Limit: <strong className="font-bold">23 Years</strong>
                </li>
                <li>
                  i.e., Candidates should not have been born earlier than
                  01/10/2001 and later than 30/09/2006.
                </li>
                <li>
                  Age relaxation is applicable as per rules.
                </li>
              </ul>
            </td>
          </tr>
          <tr>
            <td colSpan={2} className="text-center py-2">
              <span className="text-red-500 font-bold">
                Qualification
              </span>
            </td>
          </tr>
          <tr>
            <td className="py-2 pl-4 pr-2">
              <ul>
                <li>
                  Candidates should possess 12th Class or equivalent.
                </li>
              </ul>
            </td>
          </tr>
          <tr>
            <td colSpan={2} className="text-center py-2">
              <span className="text-red-500 font-bold">
                Physical Standards
              </span>
            </td>
          </tr>
          <tr>
            <td className="py-2 pl-4 pr-2">
              <ul>
                <li>
                  <strong>Physical Efficiency Test (PET):</strong> Candidates have
                  to clear 5 Kms running event in 24 minutes.
                </li>
                <li>
                  <strong>Physical Standard Test (PST):</strong> i) Height – 170
                  Cms, ii) Chest – 80-85 Cms (Minimum expansion 5 Cms)
                </li>
                <li>
                  <strong>Weight:</strong> Proportionate to height and age as per
                  medical standards.
                </li>
                <li>
                  For More details Refer Notification.
                </li>
              </ul>
            </td>
          </tr>
          <tr>
            <td colSpan={2} className="text-center py-2">
              <span className="text-red-500 font-bold">Vacancy Details</span>
            </td>
          </tr>
          <tr className="bg-gray-100">
            <td className="text-center py-2 font-medium text-gray-900">
              <span className="text-pink-500 font-bold">Post Name</span>
            </td>
            <td className="text-center py-2 font-medium text-gray-900">
              <span className="text-pink-500 font-bold">Total</span>
            </td>
          </tr>
          <tr>
            <td className="text-center py-2">
              Constable/ Fire (Male)
            </td>
            <td className="text-center py-2">
              <span className="text-black">1130</span>
            </td>
          </tr>
          <tr>
            <td colSpan={2} className="text-center py-2">
              <span className="text-blue-500 font-bold">
                Interested Candidates Can Read the Full Notification Before
                Apply Online
              </span>
            </td>
          </tr>
          <tr>
            <td colSpan={2} className="text-center py-2">
              <span className="text-red-500 font-bold">
                Important Links
              </span>
            </td>
          </tr>
          <tr>
            <td className="text-center py-2">
              <span className="text-green-500 font-bold">
                Apply Online (31-08-2024)
                <br/>
              </span>
            </td>
            <td className="text-center py-2">
              <a
                href="https://cisfrectt.cisf.gov.in/ct_fire_2024/ct_fire_login.php"
                target="_blank"
                rel="nofollow"
                className="text-blue-500 hover:underline"
              >
                <b>Click Here</b>
              </a>
            </td>
          </tr>
          <tr>
            <td className="text-center py-2">
              <span className="text-green-500 font-bold">Notification</span>
            </td>
            <td className="text-center py-2">
              <a
                title="CISF"
                href="https://img.freejobalert.com/uploads/2024/08/Notification-CISF-Constable-Fire-Male-Posts.pdf"
                target="_blank"
                rel="nofollow"
                className="text-blue-500 hover:underline"
              >
                Click Here
              </a>
            </td>
          </tr>
          <tr>
            <td className="text-center py-2">
              <span className="text-green-500 font-bold">Official Website</span>
            </td>
            <td className="text-center py-2">
              <a
                title="CISF"
                href="https://cisfrectt.cisf.gov.in/"
                target="_blank"
                rel="nofollow"
                className="text-blue-500 hover:underline"
              >
                Click Here
              </a>
            </td>
          </tr>
          <tr>
            <td className="text-center py-2">
              <span className="text-pink-500 font-bold">
                Buy Current Affairs Book (ENGLISH MEDIUM)
              </span>
            </td>
            <td className="text-center py-2">
              <a
                href="https://www.amazon.in/dp/B0DBQW76SJ/?smid=A5G76JX0GL72Y"
                target="_blank"
                rel="nofollow"
                className="text-blue-500 hover:underline"
              >
                Click here
              </a>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}