export default function RecruitmentInfo() {
  // Displays recruitment information for CISF Constable/ Fire (Male) Vacancy 2024
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-4">CISF Constable/ Fire (Male) Online Form 2024</h1>
      <div className="mb-4">
        <p className="text-gray-600 mb-2">
          <span className="font-bold text-green-500">Name of the Post:</span>
          CISF Constable/ Fire (Male) Online Form 2024
        </p>
        <p className="text-gray-600 mb-2">
          <span className="font-bold text-green-500">Post Date:</span> 22-08-2024
        </p>
        <p className="text-gray-600 mb-2">
          <span className="font-bold text-green-500">Latest Update:</span> 31-08-2024
        </p>
        <p className="text-gray-600 mb-2">
          <span className="font-bold text-green-500">Total Vacancy:</span> 1130
        </p>
      </div>
      <p className="text-gray-600 mb-4">
        <span className="font-bold text-red-500">Brief Information:</span> Central Industrial Security Force (CISF) has given a notification for the recruitment of
        Constable/ Fire (Male) Vacancy. Those Candidates who are interested in the vacancy details &amp; completed all eligibility criteria can read the
        Notification &amp; Apply Online.
      </p>

      <h2 className="text-2xl font-bold mb-4">Important Details</h2>
      <div className="mb-4">
        <table className="table-auto w-full text-left border border-gray-300">
          <tbody>
            <tr>
              <td colSpan={2} className="text-center py-2 border border-gray-300">
                <p className="font-bold text-red-500">Central Industrial Security Force (CISF)</p>
                <p className="font-bold text-green-500">Constable/ Fire (Male) Vacancy 2024</p>
                <p>
                  <a
                    href="https://www.freejobalert.com"
                    target="_blank"
                    rel="noopener"
                    className="text-blue-500 hover:underline"
                  >
                    
                  </a>
                </p>
              </td>
            </tr>
            <tr>
              <td colSpan={2} className="text-center py-2 border border-gray-300">
                <p className="font-bold text-red-500">Application Fee</p>
                <ul>
                  <li>Application Fee: <strong>Rs. 100/-</strong></li>
                  <li>For SC/ ST/ ESM Candidates: <strong>Nil</strong></li>
                  <li>Payment Mode: <strong>Through online by using Net Banking, by using Debit or Credit cards and UPI or through cash in SBI Branches by generating SBI Challan.</strong></li>
                </ul>
              </td>
            </tr>
            <tr>
              <td colSpan={2} className="text-center py-2 border border-gray-300">
                <p className="font-bold text-red-500">Important Dates</p>
                <ul>
                  <li>Starting Date to Apply Online &amp; Payment of Fee: <strong>31-08-2024</strong></li>
                  <li>Last Date to Apply Online &amp; Payment of Fee: <strong>30-09-2024 (upto 23:00 hrs)</strong></li>
                  <li>
                    candidates who wish to make the cash payment through Challan of SBI, may make the payment in cash at the Branches of SBI within the
                    working hours of the bank up to <strong>02-10-2024</strong> provided the Challan has been generated by them before{' '}
                    <strong>30-09-2024 (23:00 hours).</strong>
                  </li>
                  <li>Date of Application Form Correction Window: <strong>10-10-2024 to 12-10-2024 (23:00 hours)</strong></li>
                </ul>
              </td>
            </tr>
            <tr>
              <td colSpan={2} className="text-center py-2 border border-gray-300">
                <p className="font-bold text-red-500">Age Limit (as on 30-09-2024)</p>
                <ul>
                  <li>Minimum Age Limit: <strong>18 Years</strong></li>
                  <li>Maximum Age Limit: <strong>23 Years</strong></li>
                  <li>i.e., Candidates should not have been born earlier than 01/10/2001 and later than 30/09/2006.</li>
                  <li>Age relaxation is applicable as per rules.</li>
                </ul>
              </td>
            </tr>
            <tr>
              <td colSpan={2} className="text-center py-2 border border-gray-300">
                <p className="font-bold text-red-500">Qualification</p>
                <ul>
                  <li>Candidates should possess 12th Class or equivalent.</li>
                </ul>
              </td>
            </tr>
            <tr>
              <td colSpan={2} className="text-center py-2 border border-gray-300">
                <p className="font-bold text-red-500">Physical Standards</p>
                <ul>
                  <li>Physical Efficiency Test (PET): Candidates have to clear 5 Kms running event in 24 minutes.</li>
                  <li>
                    Physical Standard Test (PST): i) Height – 170 Cms, ii) Chest – 80-85 Cms (Minimum expansion 5 Cms)
                  </li>
                  <li>Weight: Proportionate to height and age as per medical standards.</li>
                  <li>For More details Refer Notification.</li>
                </ul>
              </td>
            </tr>
            <tr>
              <td colSpan={2} className="text-center py-2 border border-gray-300">
                <p className="font-bold text-red-500">Vacancy Details</p>
              </td>
            </tr>
            <tr>
              <td className="text-center py-2 border border-gray-300">
                <span className="font-bold text-pink-500">Post Name</span>
              </td>
              <td className="text-center py-2 border border-gray-300">
                <span className="font-bold text-pink-500">Total</span>
              </td>
            </tr>
            <tr>
              <td className="text-center py-2 border border-gray-300">&nbsp;Constable/ Fire (Male)</td>
              <td className="text-center py-2 border border-gray-300">
                <span className="text-gray-600">1130</span>
              </td>
            </tr>
            <tr>
              <td colSpan={2} className="text-center py-2 border border-gray-300">
                <span className="font-bold text-blue-500">Interested Candidates Can Read the Full Notification Before Apply Online</span>
              </td>
            </tr>
            <tr>
              <td colSpan={2} className="text-center py-2 border border-gray-300">
                <p className="font-bold text-red-500">Important Links</p>
              </td>
            </tr>
            <tr>
              <td className="text-center py-2 border border-gray-300">
                <span className="font-bold text-green-500">Apply Online (31-08-2024)</span>
              </td>
              <td className="text-center py-2 border border-gray-300">
                <a
                  href="https://cisfrectt.cisf.gov.in/ct_fire_2024/ct_fire_login.php"
                  target="_blank"
                  rel="nofollow"
                  className="text-blue-500 hover:underline"
                >
                  <b>Click Here</b>
                </a>
              </td>
            </tr>
            <tr>
              <td className="text-center py-2 border border-gray-300">
                <span className="font-bold text-green-500">Notification</span>
              </td>
              <td className="text-center py-2 border border-gray-300">
                <a
                  title="CISF"
                  href="https://img.freejobalert.com/uploads/2024/08/Notification-CISF-Constable-Fire-Male-Posts.pdf"
                  target="_blank"
                  rel="nofollow"
                  className="text-blue-500 hover:underline"
                >
                  Click Here
                </a>
              </td>
            </tr>
            <tr>
              <td className="text-center py-2 border border-gray-300">
                <span className="font-bold text-green-500">Official Website</span>
              </td>
              <td className="text-center py-2 border border-gray-300">
                <a
                  title="CISF"
                  href="https://cisfrectt.cisf.gov.in/"
                  target="_blank"
                  rel="nofollow"
                  className="text-blue-500 hover:underline"
                >
                  Click Here
                </a>
              </td>
            </tr>
            <tr>
              <td className="text-center py-2 border border-gray-300">
                <span className="font-bold text-pink-500">Buy Current Affairs Book (ENGLISH MEDIUM)</span>
              </td>
              <td className="text-center py-2 border border-gray-300">
                <a
                  href="https://www.amazon.in/dp/B0DBQW76SJ/?smid=A5G76JX0GL72Y"
                  target="_blank"
                  rel="nofollow"
                  className="text-blue-500 hover:underline"
                >
                  Click here
                </a>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
}