export default function RecruitmentInformation() {
  // Displays recruitment information for CISF Constable/ Fire (Male) 2024
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-4">CISF Constable/ Fire (Male) Online Form 2024</h1>
      <div className="mb-4">
        <p className="text-lg font-medium mb-2">
          <span className="text-green-500 font-bold">Name of the Post:</span> CISF Constable/ Fire (Male) Online Form 2024
        </p>
        <p className="text-lg font-medium mb-2">
          <span className="text-green-500 font-bold">Post Date:</span> 22-08-2024
        </p>
        <p className="text-lg font-medium mb-2">
          <span className="text-green-500 font-bold">Latest Update:</span> 31-08-2024
        </p>
        <p className="text-lg font-medium mb-2">
          <span className="text-green-500 font-bold">Total Vacancy:</span> 1130
        </p>
      </div>
      <p className="mb-4">
        <span className="text-red-500 font-bold">Brief Information:</span> Central Industrial Security Force (CISF) has given a notification for the recruitment of Constable/ Fire (Male) Vacancy. Those Candidates who are interested in the vacancy details & completed all eligibility criteria can read the Notification & Apply Online.
      </p>
      <h2 className="text-2xl font-bold mb-4">Central Industrial Security Force (CISF)</h2>
      <h3 className="text-xl font-bold mb-4">Constable/ Fire (Male) Vacancy 2024</h3>
      <p className="text-center mb-4"><a href="https://www.freejobalert.com" target="_blank" rel="noopener" className="text-blue-500 hover:underline"></a></p>
      <table className="table-auto w-full border-collapse border border-gray-300 mb-4">
        <tbody>
          <tr>
            <td colSpan="2" className="text-center p-2">
              <p className="text-red-500 font-bold">Application Fee</p>
              <ul className="list-disc ml-6">
                <li className="text-left">Application Fee: <strong>Rs. 100/-</strong></li>
                <li className="text-left">For SC/ ST/ ESM Candidates: <strong>Nil</strong></li>
                <li className="text-left">Payment Mode: <strong>Through online by using Net Banking, by using Debit or Credit cards and UPI or through cash in SBI Branches by generating SBI Challan.</strong></li>
              </ul>
            </td>
          </tr>
          <tr>
            <td colSpan="2" className="text-center p-2">
              <p className="text-red-500 font-bold">Important Dates</p>
              <ul className="list-disc ml-6">
                <li className="text-left">Starting Date to Apply Online & Payment of Fee: <strong>31-08-2024</strong></li>
                <li className="text-left">Last Date to Apply Online & Payment of Fee: <strong>30-09-2024 (upto 23:00 hrs)</strong></li>
                <li className="text-left">candidates who wish to make the cash payment through Challan of SBI, may make the payment in cash at the Branches of SBI within the working hours of the bank up to <strong>02-10-2024</strong> provided the Challan has been generated by them before <strong>30-09-2024 (23:00 hours).</strong></li>
                <li className="text-left">Date of Application Form Correction Window: <strong>10-10-2024 to 12-10-2024 (23:00 hours)</strong></li>
              </ul>
            </td>
          </tr>
          <tr>
            <td colSpan="2" className="text-center p-2">
              <p className="text-red-500 font-bold">Age Limit (as on 30-09-2024)</p>
              <ul className="list-disc ml-6">
                <li className="text-left">Minimum Age Limit: <strong>18 Years</strong></li>
                <li className="text-left">Maximum Age Limit: <strong>23 Years</strong></li>
                <li className="text-left">i.e., Candidates should not have been born earlier than 01/10/2001 and later than 30/09/2006.</li>
                <li className="text-left">Age relaxation is applicable as per rules.</li>
              </ul>
            </td>
          </tr>
          <tr>
            <td colSpan="2" className="text-center p-2">
              <p className="text-red-500 font-bold">Qualification</p>
              <ul className="list-disc ml-6">
                <li className="text-left">Candidates should possess 12th Class or equivalent.</li>
              </ul>
            </td>
          </tr>
          <tr>
            <td colSpan="2" className="text-center p-2">
              <p className="text-red-500 font-bold">Physical Standards</p>
              <ul className="list-disc ml-6">
                <li className="text-left"><strong>Physical Efficiency Test (PET):</strong> Candidates have to clear 5 Kms running event in 24 minutes.</li>
                <li className="text-left"><strong>Physical Standard Test (PST): </strong>i) Height – 170 Cms, ii) Chest – 80-85 Cms (Minimum expansion 5 Cms)</li>
                <li className="text-left"><strong>Weight:</strong> Proportionate to height and age as per medical standards.</li>
                <li className="text-left">For More details Refer Notification.</li>
              </ul>
            </td>
          </tr>
          <tr>
            <td colSpan="2" className="text-center p-2">
              <p className="text-red-500 font-bold">Vacancy Details</p>
            </td>
          </tr>
          <tr>
            <td className="text-center p-2"><span className="text-blue-500 font-bold">Post Name</span></td>
            <td className="text-center p-2"><span className="text-blue-500 font-bold">Total</span></td>
          </tr>
          <tr>
            <td className="text-center p-2">&nbsp;Constable/ Fire (Male)</td>
            <td className="text-center p-2"><span className="text-black">1130</span></td>
          </tr>
          <tr>
            <td colSpan="2" className="text-center p-2">
              <p className="text-blue-500 font-bold">Interested Candidates Can Read the Full Notification Before Apply Online</p>
            </td>
          </tr>
          <tr>
            <td colSpan="2" className="text-center p-2">
              <p className="text-red-500 font-bold">Important Links</p>
            </td>
          </tr>
          <tr>
            <td className="text-center p-2"><span className="text-green-500 font-bold">Apply Online (31-08-2024)<br/></span></td>
            <td className="text-center p-2"><a href="https://cisfrectt.cisf.gov.in/ct_fire_2024/ct_fire_login.php" target="_blank" rel="nofollow" className="text-blue-500 hover:underline"><b>Click Here</b></a></td>
          </tr>
          <tr>
            <td className="text-center p-2"><span className="text-green-500 font-bold">Notification</span></td>
            <td className="text-center p-2"><a title="CISF" href="https://img.freejobalert.com/uploads/2024/08/Notification-CISF-Constable-Fire-Male-Posts.pdf" target="_blank" rel="nofollow" className="text-blue-500 hover:underline">Click Here</a></td>
          </tr>
          <tr>
            <td className="text-center p-2"><span className="text-green-500 font-bold">Official Website</span></td>
            <td className="text-center p-2"><a title="CISF" href="https://cisfrectt.cisf.gov.in/" target="_blank" rel="nofollow" className="text-blue-500 hover:underline"><strong>Click Here</strong></a></td>
          </tr>
          <tr>
            <td className="text-center p-2"><span className="text-blue-500 font-bold">Buy Current Affairs Book (ENGLISH MEDIUM)</span></td>
            <td className="text-center p-2"><a href="https://www.amazon.in/dp/B0DBQW76SJ/?smid=A5G76JX0GL72Y" target="_blank" rel="nofollow" className="text-blue-500 hover:underline">Click here</a></td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}